# Run scheduled (rolling) jobs on a nightly basis, as your crate may break independently of any
# given PR. E.g., updates to rust nightly and updates to this crates dependencies. See check.yml for
# information about how the concurrency cancellation and workflow triggering works
permissions:
  contents: read

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "7 7 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: rolling

env:
  UV_VERSION: "0.9.1"

jobs:
  # https://twitter.com/alcuadrado/status/1571291687837732873
  update:
    # This action checks that updating the dependencies of this crate to the latest available that
    # satisfy the versions in pyproject.toml does not break this crate. This is important as consumers
    # of this crate will generally use the latest available crates. This is subject to the standard
    # Cargo semver rules (i.e cargo does not update to a new major version unless explicitly told
    # to).
    runs-on: ubuntu-latest
    name: ubuntu / ${{ matrix.python-version }} / updates work
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    # There's no point running this if no uv.lock was checked in in the first place, since we'd
    # just redo what happened in the regular test job. Unfortunately, hashFiles only works in if on
    # steps, so we repeat it.
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          persist-credentials: false
          submodules: true

      - name: Set up uv
        if: hashFiles('uv.lock') != ''
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # 7.1.0
        with:
          version: ${{ env.UV_VERSION }}
          enable-cache: true

      - name: Install ${{ matrix.python-version }}
        if: hashFiles('uv.lock') != ''
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: uv sync --dev --upgrade
        if: hashFiles('uv.lock') != ''
        run: uv sync --dev --upgrade --all-packages --all-extras

      - name: make test
        if: hashFiles('uv.lock') != ''
        run: make test

  # https://github.com/marketplace/actions/alls-green#why used for branch protection checks
  rolling-check:
    if: always()
    needs:
      # - nightly
      - update
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
